name: coverage-check

on: 
  - push

jobs:
  coverage-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
      - name: install1
        run:  pip install poetry
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: e40f025c294d5cd9033eb3c89f4e5b8e1dad0589b6994885f81c1150b9137530
        with:
          coverageCommand: make coverage
      - name: install2
        run: make install
      - name: install3
        run: pip install pytest   
      - name: run-checker
        run:  make coverage

      
