name: test-check

on: 
  - push

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-python
        uses: actions/setup-python@v2
      - name: install1
        run:  pip install poetry
      - name: install2
        run: make install
      - name: install3
        run: pip install pytest   
      - name: run-tester
        run:  make test
